# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Habiteeth' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Habiteeth
    pod 'RxSwift',    '~> 3.4'
    pod 'RxCocoa',    '~> 3.4'
    pod 'SnapKit'
    pod 'Alamofire', '~> 4.5'
    pod 'RxBluetoothKit'

    target 'HabiteethUITests' do
        inherit! :search_paths

        # Swift test
        pod 'Quick', '~> 1.1'
        pod 'Nimble', '~> 7.0'
        # Pods for testing
    end
end